package orchis

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/jaycee1285/base16changer/internal/scheme"
	"github.com/jaycee1285/base16changer/internal/template"
)

//go:embed all:src
var srcFS embed.FS

// Variant selects light or dark theme compilation
type Variant string

const (
	Light Variant = "light"
	Dark  Variant = "dark"
)

// Build compiles the Orchis theme with base16 colors and writes it to destDir.
// destDir is the parent themes directory (e.g. ~/.local/share/themes).
// It creates Orchis-Light-Compact or Orchis-Dark-Compact under destDir.
func Build(s *scheme.Base16, variant Variant, destDir string) error {
	// Extract embedded SCSS to a temp directory
	tmpDir, err := os.MkdirTemp("", "orchis-scss-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	if err := extractEmbedded(tmpDir); err != nil {
		return fmt.Errorf("extract scss: %w", err)
	}

	srcDir := filepath.Join(tmpDir, "src")
	sassDir := filepath.Join(srcDir, "_sass")

	// 1. Render and write the color palette
	palette, err := renderPalette(s)
	if err != nil {
		return fmt.Errorf("render palette: %w", err)
	}
	if err := os.WriteFile(filepath.Join(sassDir, "_color-palette-default.scss"), []byte(palette), 0644); err != nil {
		return fmt.Errorf("write palette: %w", err)
	}

	// 2. Write _tweaks-temp.scss with $theme: 'base16'
	tweaksOrig, err := os.ReadFile(filepath.Join(sassDir, "_tweaks.scss"))
	if err != nil {
		return fmt.Errorf("read tweaks: %w", err)
	}
	tweaksContent := strings.Replace(string(tweaksOrig), "$theme: 'default'", "$theme: 'base16'", 1)
	if err := os.WriteFile(filepath.Join(sassDir, "_tweaks-temp.scss"), []byte(tweaksContent), 0644); err != nil {
		return fmt.Errorf("write tweaks-temp: %w", err)
	}

	// 3. Compile the selected variant
	var themeName, scssName string
	switch variant {
	case Light:
		themeName = "Orchis-Light-Compact"
		scssName = "gtk-Light-Compact.scss"
	case Dark:
		themeName = "Orchis-Dark-Compact"
		scssName = "gtk-Dark-Compact.scss"
	default:
		return fmt.Errorf("unknown variant: %s", variant)
	}

	themeDir := filepath.Join(destDir, themeName)

	// GTK 4
	gtk4Out := filepath.Join(themeDir, "gtk-4.0", "gtk.css")
	if err := compileSCSS(filepath.Join(srcDir, "gtk", "4.0", scssName), gtk4Out); err != nil {
		return fmt.Errorf("compile gtk-4.0: %w", err)
	}

	// GTK 3
	gtk3Out := filepath.Join(themeDir, "gtk-3.0", "gtk.css")
	if err := compileSCSS(filepath.Join(srcDir, "gtk", "3.0", scssName), gtk3Out); err != nil {
		return fmt.Errorf("compile gtk-3.0: %w", err)
	}

	// Write index.theme
	indexTheme := fmt.Sprintf(`[Desktop Entry]
Type=X-GNOME-Metatheme
Name=%s
Comment=Orchis theme with base16 colors
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=%s
MetacityTheme=%s
IconTheme=Tela-circle
CursorTheme=Vimix
ButtonLayout=close,minimize,maximize:menu
`, themeName, themeName, themeName)
	if err := os.WriteFile(filepath.Join(themeDir, "index.theme"), []byte(indexTheme), 0644); err != nil {
		return fmt.Errorf("write index.theme: %w", err)
	}

	// Also write to ~/.config/gtk-4.0/gtk.css for libadwaita apps
	home, _ := os.UserHomeDir()
	libadwaitaCSS := filepath.Join(home, ".config", "gtk-4.0", "gtk.css")
	gtk4Content, err := os.ReadFile(gtk4Out)
	if err != nil {
		return fmt.Errorf("read compiled gtk4: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(libadwaitaCSS), 0755); err != nil {
		return fmt.Errorf("mkdir gtk-4.0 config: %w", err)
	}
	if err := os.WriteFile(libadwaitaCSS, gtk4Content, 0644); err != nil {
		return fmt.Errorf("write libadwaita css: %w", err)
	}

	return nil
}

// ThemeName returns the GTK theme name for the given variant
func ThemeName(variant Variant) string {
	switch variant {
	case Light:
		return "Orchis-Light-Compact"
	case Dark:
		return "Orchis-Dark-Compact"
	default:
		return "Orchis-Light-Compact"
	}
}

func extractEmbedded(destDir string) error {
	return fs.WalkDir(srcFS, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		target := filepath.Join(destDir, path)

		if d.IsDir() {
			return os.MkdirAll(target, 0755)
		}

		data, err := srcFS.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read embedded %s: %w", path, err)
		}

		return os.WriteFile(target, data, 0644)
	})
}

func compileSCSS(input, output string) error {
	dir := filepath.Dir(output)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}

	cmd := exec.Command("sassc", "-M", "-t", "expanded", input, output)
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("sassc %s: %w", filepath.Base(input), err)
	}
	return nil
}

const paletteTemplate = `// Orchis Color Palette — generated by base16changer
// Scheme: {{scheme-name}}
// Author: {{scheme-author}}

// Accent (from base16 accent field, falls back to base0D)
$accent: #{{accent-hex}};

// Red (base08 → destructive/error)
$red-light: #{{base08-hex}};
$red-dark: #{{base08-hex}};

// Pink (base0E)
$pink-light: #{{base0E-hex}};
$pink-dark: #{{base0E-hex}};

// Purple (base0E)
$purple-light: #{{base0E-hex}};
$purple-dark: #{{base0E-hex}};

// Blue (base0D)
$blue-light: #{{base0D-hex}};
$blue-dark: #{{base0D-hex}};

// Teal (base0C)
$teal-light: #{{base0C-hex}};
$teal-dark: #{{base0C-hex}};

// Green (base0B → success)
$green-light: #{{base0B-hex}};
$green-dark: #{{base0B-hex}};
$sea-light: #{{base0B-hex}};
$sea-dark: #{{base0B-hex}};

// Yellow (base0A → warning)
$yellow-light: #{{base0A-hex}};
$yellow-dark: #{{base0A-hex}};

// Orange (base09)
$orange-light: #{{base09-hex}};
$orange-dark: #{{base09-hex}};

// Grey scale — derived from the active Base16 neutral ramp
$grey-050: #{{grey-050-hex}};
$grey-100: #{{grey-100-hex}};
$grey-150: #{{grey-150-hex}};
$grey-200: #{{grey-200-hex}};
$grey-250: #{{grey-250-hex}};
$grey-300: #{{grey-300-hex}};
$grey-350: #{{grey-350-hex}};
$grey-400: #{{grey-400-hex}};
$grey-450: #{{grey-450-hex}};
$grey-500: #{{grey-500-hex}};
$grey-550: #{{grey-550-hex}};
$grey-600: #{{grey-600-hex}};
$grey-650: #{{grey-650-hex}};
$grey-700: #{{grey-700-hex}};
$grey-750: #{{grey-750-hex}};
$grey-800: #{{grey-800-hex}};
$grey-850: #{{grey-850-hex}};
$grey-900: #{{grey-900-hex}};
$grey-950: #{{grey-950-hex}};

// White-like high surface — derived from the active scheme instead of hard white
$white: #{{grey-050-hex}};

// Black
$black: #000000;

// Window Buttons
$button-close: #fd5f51;
$button-max: #38c76a;
$button-min: #fdbe04;
`

func renderPalette(s *scheme.Base16) (string, error) {
	return template.RenderString(paletteTemplate, s.ToMap())
}
